name: suberjet_clean_architecture
description: SuberJet App Travel between Cities

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.2.1+1
  equatable: ^2.0.5
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_getit: ^1.2.1
  flutter_inappwebview: ^5.7.2+3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.23.0
  get_it: ^7.6.0
  internet_connection_checker: ^1.0.0+1
  modal_bottom_sheet: ^3.0.0-pre
  molten_navigationbar_flutter: ^1.0.1
  shared_preferences: ^2.2.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - lang/ar.json
    - lang/en.json
    - assets/home/
    - assets/seats/
    - assets/images/
    - assets/images/splashLogo.png
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: TheSansArabic
      fonts:
        - asset: assets/fonts/Sj.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
